Build specs
dolittle/DotNET.Applications pull request #133
Opened 2018-10-04 05:56 UTC by woksin

Specs around most of the vital parts of the Build Tool

Also added lots of headers

2018-10-04 06:47 UTC, einari requested changes
Wow.. Great to see specs coming in here. And they look very correct for what they're speccing out.
Impressive catch up going on here! Kudos.

I have a couple of comments that I see as a pattern throughout. Since the PR was sooo big, I didn't take the time to go and put in all the comments for all the files as I saw quickly a pattern and you should just go through the specs and make it consistently follow.
Thing of specs as reading regular English, leave the realm of types. Describe what you're trying to accomplish through behaviors. Therefor you should consistently not have the ActualTypeName in the middle of a **given**, **when** or **then** statement, but rather actual_type_name or something better that actually leaves the type behind altogether. 

Follow same principles as we apply to the rest of the code - don't treat code differently; code is code.

Be clear about the intent of the behavior and it should reflect what the "Because of" is actually doing- this makes it clear and would also make it follow the single responsibility principle itself. 

Really like the nested "for_" thinking. This is something that would be great to look into formalizing - we should have a section in our documentation on how we think about specifications in general - regardless of programming language, our structure and thinking behind it.  Maybe something to have in our "Home" repository - as it does not belong to any concrete repository.

2018-10-04 06:47 UTC, einari commented on Specifications/Build/for_Artifact/for_ArtifactsConfigurationBuilder/when_not_using_modules/when_building_artifacts_with_an_empty_ArtifactsConfiguration.cs
> +        It should_generate_an_artifacts_configuration_when_building_with_all_used_types = () => result_configuration.ShouldNotBeNull();
Name of the "then" could just be: "It should_return_an_instance" for this particular one.

2018-10-04 06:47 UTC, einari commented on Specifications/Build/for_Artifact/for_ArtifactsConfigurationBuilder/when_not_using_modules/when_building_artifacts_with_an_empty_ArtifactsConfiguration.cs
> +        It should_generate_an_artifacts_configuration_with_feature1 = () => result_configuration.Artifacts.ContainsKey(feature1).ShouldBeTrue();
Since the when statement is stating you're building something ("when building artifacts with an... " - you can skip the "_generate_an_artifacts_configuration_" instead have "It should_have_the_first_feature".  I would argue you probably don't need this spec here at all, since thats not what you're really asserting. You could hold this separate. In this particular case, you're speccing that it is an empty configuration object. And I'm beginning to think there is something a little bit unaligned here as well. If its empty, why does it have all these things on it. Another point is on readability - "feature1", "feature2", if there should be a feature - we need to understand why and what - if they serve a purpose. If they're just there for testing from a datadriven perspective of diversity in data - you could have "first_feature" and "second_feature". If data diversity is important and how the feature looks like, you might want to consider explicitly putting these in specific specs.

2018-10-04 06:47 UTC, einari commented on Specifications/Build/for_Artifact/for_ArtifactsConfigurationBuilder/when_not_using_modules/when_building_artifacts_with_an_empty_ArtifactsConfiguration.cs
> +    public class when_building_artifacts_with_an_empty_ArtifactsConfiguration : given.an_empty_ArtifactsConfiguration
Stick with one naming standard; ArtifactsConfiguration => artifacts_configuration

2018-10-04 06:47 UTC, einari commented on Specifications/Build/for_Artifact/for_ArtifactsConfigurationBuilder/when_using_modules/given/a_bounded_context_config.cs
> +    public class a_bounded_context_config : Dolittle.Build.given.an_ILogger
If something has dependencies that needs to be fulfilled and you want to do this only once, create a given statement that is "all_dependencies" instead of "an_ILogger" - then that can expand later

2018-10-04 06:47 UTC, einari commented on Specifications/Build/for_Artifact/for_ArtifactsConfigurationBuilder/when_using_modules/when_building_artifacts_with_an_empty_ArtifactsConfiguration.cs
> +    public class when_building_artifacts_with_an_empty_ArtifactsConfiguration : given.an_empty_ArtifactsConfiguration
Same comments as earlier here

2018-10-04 06:47 UTC, einari commented on Specifications/Build/for_Artifact/for_ArtifactsConfigurationExtensions/for_GetAllArtifactDefinitions/when_getting_all_artifact_definitions.cs
> +namespace Dolittle.Build.Artifact.for_Artifact.for_ArtifactsConfigurationExtensions.for_GetAllArtifactDefinitions
This is a nice way to group things. Having a "for_" on the unit level and then a nested "for_" for methods. Nice.

2018-10-04 06:47 UTC, einari commented on Specifications/Build/for_Artifact/for_ArtifactsConfigurationExtensions/for_GetAllArtifactDefinitions/when_getting_all_artifact_definitions.cs
> +    public class when_getting_all_artifact_definitions: given.an_ArtifactConfiguration_with_two_features
Consistent naming; artifacts_configuration

2018-10-04 06:47 UTC, einari commented on Specifications/Build/for_Artifact/for_ArtifactsConfigurationExtensions/for_GetAllArtifactDefinitions/when_getting_all_artifact_definitions_of_a_type.cs
> +    public class when_getting_all_artifact_definitions_of_a_type: given.an_ArtifactConfiguration_with_two_features
Naming consistency; ArtifactConfiguration => artifact_configuration

2018-10-04 06:47 UTC, einari commented on Specifications/Build/for_Artifact/for_ArtifactsConfigurationExtensions/for_ValidateArtifacts/when_not_using_modules/given/an_ArtifactsConfiguration.cs
> +            feature1_artifacts_definition_by_type.Commands = new []{command_artifact_1};
Its more readable with "first_", "second_" than postfix with a number

2018-10-04 06:47 UTC, einari commented on Specifications/Build/for_Artifact/for_ArtifactsConfigurationExtensions/given/an_ArtifactConfiguration_with_two_features.cs
> +        protected static readonly List<ArtifactDefinition> all_artifact_definitions = new List<ArtifactDefinition>();
Unless you're going to change the content of "all_artifact_definitions" and the other properties here, they don't need to be List<>. You can keep them as IEnumerable and then instantiate them in the "Establish context" lambda.
We follow the same rules here as we do with the rest of our code.

2018-10-04 06:47 UTC, einari commented on Specifications/Build/for_Topology/for_StringExtensions/for_GetFeatureFromPath/when_getting_feature_from_path_with_no_feature.cs
> +            exception_result_for_empty_path = Catch.Exception(() => empty_path.GetFeatureFromPath());
Your spec says "when_getting_feature_from_path_with_no_feature", but you have 4 different specs in it.
Think of "Because of" as doing one thing and then formulate the "when_" according to what you're doing. 
Keeps your specs very focused and abiding by SRP

2018-10-04 06:47 UTC, einari commented on Specifications/Build/for_Topology/for_StringExtensions/for_GetFeatureFromPath/when_getting_feature_from_path_with_three_features.cs
> +        It should_should_have_first_FeatureDefinition_with_correct_name = () => feature_definition.Name.ShouldEqual((FeatureName)feature1_name);
Great 👍  Here you have the convention of "first_", "second_"..  But the "FeatureDefinition" should be "feature_definition".

2018-10-06 14:24 UTC, einari commented
This looks really great..   I just had a question with regards to lack of use of specific exceptions with a descriptive text saying what is allowed and expected for string format for Feature.  Other than that - looks really good. 

Awaiting your comments on that or possibly change if it makes sense.

2018-10-06 17:34 UTC, woksin commented
Yeah you're right, @einari . I'll probably just throw an ArgumentException there

2018-10-07 06:03 UTC, einari commented
I was actually more thinking of custom exceptions - sorry for being unclear. But I'll merge it in - not that important here.

2018-10-07 06:04 UTC, einari approved these changes

2018-10-07 06:04 UTC, einari commented on Specifications/Build/for_Topology/for_StringExtensions/for_GetFeatureFromPath/when_getting_feature_from_path_containing_a_dash.cs
> +        It should_throw_an_exception = () => exception_result_for_path_containing_dash.ShouldNotBeNull();
I see the implementation just throws a regular `Exception` - should this be more specific? 
Something like `InvalidFeatureException` or `FeatureContainsInvalidCharaceters` and then a string telling which characters are allowed?

The `then` would then be : 

```csharp
It should_throw_feature_contains_invalid_characters = () => result.ShouldBeOfExactType<FeatureContainsInvalidCharacters>()
```

2018-10-07 06:04 UTC, einari commented on Specifications/Build/for_Topology/for_StringExtensions/for_GetFeatureFromPath/when_getting_feature_from_path_containing_space.cs
> +        It should_throw_an_exception = () => exception_result_for_path_containing_whitespace.ShouldNotBeNull();
Same as for the comment on 
https://github.com/dolittle/DotNET.SDK/pull/133/commits/de609ae067352c0c04716d54eba00ae7917f456c#diff-2908b2e35b65192570806eb764e76d0c

2018-10-07 06:04 UTC, merged