Upgrade to new contracts
dolittle/DotNET.Applications pull request #282
Opened 2020-05-12 07:04 UTC by jakhog

Will write something here later...

2020-05-12 09:01 UTC, woksin requested changes
Great stuff! This also makes it easier for us to do the SDK split later and being able to build event handlers on the fly. I have a couple of comments though, but the logics seems intact.

2020-05-12 09:01 UTC, woksin commented on Source/EventHorizon/SubscriptionBootProcedurePolicy.cs
> +                        }
Wouldn't it be more clear to use `if` in this case? This code was a bit hard to understand, but doesn't this suggestion do the same?
```suggestion
                        if (_ is RpcException rpcException && rpcException.StatusCode == StatusCode.Unavailable)
                        {
                            return true;
                        }
                        _logger.Warning(_, "Error while subscribing to event horizon");
                         return true;
```

2020-05-12 09:01 UTC, woksin commented on Source/EventHorizon/SubscriptionResponse.cs
> +            if (failure != null) Failure = failure;
Unnecessary check for `null`. The default value of the `Failure`-property is `null` so there is no reason to check for `null`
```suggestion
            Failure = failure;
```

2020-05-12 09:01 UTC, woksin commented on Source/Events.Filters/EventFiltersProvider.cs
> +            _logger.Debug("Providing {FilterCount} unpartitioned event filters", _unpartitionedFilters.Count());
Does it make more sense if this is a `Trace`?
```suggestion
            _logger.Trace("Providing {FilterCount} unpartitioned event filters", _unpartitionedFilters.Count());
```

2020-05-12 09:01 UTC, woksin commented on Source/Events.Filters/EventFiltersProvider.cs
> +            _logger.Debug("Providing {FilterCount} partitioned event filters", _partitionedFilters.Count());
Does it make more sense if this is a `Trace`?
```suggestion
            _logger.Trace("Providing {FilterCount} partitioned event filters", _partitionedFilters.Count());
```

2020-05-12 09:01 UTC, woksin commented on Source/Events.Filters/EventHorizon/PublicEventsFilterProvider.cs
> +            _logger.Debug("Providing {FilterCount} public event filters", _filters.Count());
Does it make more sense if this is a `Trace`?
```suggestion
            _logger.Trace("Providing {FilterCount} public event filters", _filters.Count());
```

2020-05-12 09:01 UTC, woksin commented on Source/Events.Filters/EventHorizon/PublicFilterResult.cs
> +    public class PublicFilterResult : PartitonedFilterResult
Typo
```suggestion
    public class PublicFilterResult : PartitionedFilterResult
```

2020-05-12 09:01 UTC, woksin commented on Source/Events.Filters/FilterManager.cs
> +    public class FilterManager : IFilterManager
I think that it makes sense to call this Filters and IFilters instead of having the *Manager prefix

2020-05-12 09:01 UTC, woksin commented on Source/Events.Filters/FilterManagerPolicy.cs
> +    public class FilterManagerPolicy : IDefineAsyncPolicyForType
FilterManagerPolicy => FiltersPolicy (read comment above)

2020-05-12 09:01 UTC, woksin commented on Source/Events.Filters/FilterManagerPolicy.cs
> +                        }
Wouldn't it be more clear to use `if` in this case? This code was a bit hard to understand, but doesn't this suggestion do the same?
```suggestion
                        if (_ is RpcException rpcException && rpcException.StatusCode == StatusCode.Unavailable)
                        {
                            return true;
                        }
                        _logger.Warning(_, "Error while registering filter");
                         return true;
```

2020-05-12 09:01 UTC, woksin commented on Source/Events.Filters/IFilterManager.cs
> +    public interface IFilterManager
As I commented above. IFilterManager => IFilters

2020-05-12 09:01 UTC, woksin commented on Source/Events.Filters/Internal/AbstractFilterProcessor.cs
> +        }
I would have a method to check if event type is incorrect and have that throw the exception. Like this:
```suggestion
        protected override Task<TFilterResponse> Handle(FilterEventRequest request, CancellationToken cancellationToken)
        {
            var converted = _converter.ToSDK(request.Event);
            ThrowIfIncorrectEventType(converted.Event.GetType());
            var context = new EventContext(converted.EventSource, converted.Occurred);
            return Filter(typedEvent, context);
        }
        void ThrowIfIncorrectEventType(Type eventType)
        {
            if (eventType != typeof(TEventType))
            {
                throw new EventTypeIsIncorrectForFilter(typeof(TEventType), eventType);
            }
        }
```

2020-05-12 09:01 UTC, woksin commented on Source/Events.Filters/Internal/FilterProcessors.cs
> +        public EventFilterProcessor ProcessorFor(FilterId id, ScopeId scope, ICanFilterEvents filter)
Since the class is named FilterProcessors would it make sense to call the method `GetFor` instead of `ProcessorFor` since the 'Processor' part is implicit
```suggestion
        public EventFilterProcessor GetFor(FilterId id, ScopeId scope, ICanFilterEvents filter)
```

2020-05-12 09:01 UTC, woksin commented on Source/Events.Filters/Internal/FilterProcessors.cs
> +        public EventFilterWithPartitionsProcessor ProcessorFor(FilterId id, ScopeId scope, ICanFilterEventsWithPartition filter)
Since the class is named FilterProcessors would it make sense to call the method `GetFor` instead of `ProcessorFor` since the 'Processor' part is implicit
```suggestion
        public EventFilterWithPartitionsProcessor GetFor(FilterId id, ScopeId scope, ICanFilterEventsWithPartition filter)
```

2020-05-12 09:01 UTC, woksin commented on Source/Events.Filters/Internal/FilterProcessors.cs
> +        public PublicEventFilterProcessor ProcessorFor(FilterId id, ICanFilterPublicEvents filter)
Since the class is named FilterProcessors would it make sense to call the method `GetFor` instead of `ProcessorFor` since the 'Processor' part is implicit
```suggestion
        public PublicEventFilterProcessor GetFor(FilterId id, ICanFilterPublicEvents filter)
```

2020-05-12 09:01 UTC, woksin commented on Source/Events.Filters/Internal/ICanFilter.cs
> +    public interface ICanFilter<TEventType, TFilterResult>
It does seem a little weird that this class is called ICanFilter when it is really filtering events, and the other interfaces that implements this interface is called 'ICanFilter***Events'. I can see why it's done, but it just doesn't ring. I don't think that calling it `ICanFilterEvent` either would make sense with how it is now.

2020-05-12 09:01 UTC, woksin commented on Source/Events.Filters/PartitonedFilterResult.cs
> +    public class PartitonedFilterResult : FilterResult
Typo
```suggestion
    public class PartitionedFilterResult : FilterResult
```

2020-05-12 09:01 UTC, woksin commented on Source/Events.Handling/Builder/EventHandlerInstanceBuilder.cs
> +        where TEventType : IEvent
Doesn't THandlerType need to have the generic constrain `class`?
```suggestion
        where THandlerType : class
        where TEventType : IEvent
```

2020-05-12 09:01 UTC, woksin commented on Source/Events.Handling/Builder/EventHandlerMethod.cs
> +        where TEventType : IEvent;
As the comment above
```suggestion
        where THandlerType : class
        where TEventType : IEvent;
```

2020-05-12 09:01 UTC, woksin commented on Source/Events.Handling/ConventionEventHandlerBuilder.cs
> +        public static IEventHandler<TEventType> BuildFor<THandlerType>(FactoryFor<THandlerType> factory)
As comment above
```suggestion
        public static IEventHandler<TEventType> BuildFor<THandlerType>(FactoryFor<THandlerType> factory)
        where THandlerType : class
```

2020-05-12 09:01 UTC, woksin commented on Source/Events.Handling/ConventionEventHandlerBuilder.cs
> +                    }
Would be nice to have these as ThrowIf* methods and put them on top of the method

2020-05-12 09:01 UTC, woksin commented on Source/Events.Handling/ConventionEventHandlerBuilder.cs
> +                }
Also ThrowIf* method

2020-05-12 09:01 UTC, woksin commented on Source/Events.Handling/EventHandlerManager.cs
> +    public class EventHandlerManager : IEventHandlerManager
As with the comment for `IFIlterManager`, `EventHandlerManager`=> `EventHandlers`

2020-05-12 09:01 UTC, woksin commented on Source/Events.Handling/EventHandlerManagerPolicy.cs
> +    public class EventHandlerManagerPolicy : IDefineAsyncPolicyForType
As comment above

2020-05-12 09:01 UTC, woksin commented on Source/Events.Handling/EventHandlerManagerPolicy.cs
> +                        }
Wouldn't it be more clear to use `if` in this case? This code was a bit hard to understand, but doesn't this suggestion do the same?
```suggestion
                        if (_ is RpcException rpcException && rpcException.StatusCode == StatusCode.Unavailable)
                        {
                            return true;
                        }
                        _logger.Warning(_, "Error while registering event handler");
                         return true;
```

2020-05-12 09:01 UTC, woksin commented on Source/Events.Handling/EventHandlersProvider.cs
> +            _logger.Debug("Providing {EventHandlerCount} event handlers", _handlers.Count());
Does it make more sense for this to be `Trace`?
```suggestion
            _logger.Trace("Providing {EventHandlerCount} event handlers", _handlers.Count());
```

2020-05-12 09:01 UTC, woksin commented on Source/Events.Handling/EventHorizon/ExternalEventHandlersProvider.cs
> +            _logger.Debug("Providing {EventHandlerCount} external event handlers", _handlers.Count());
Does it make more sense for this to be `Trace`?
```suggestion
            _logger.Trace("Providing {EventHandlerCount} external event handlers", _handlers.Count());
```

2020-05-12 09:01 UTC, woksin commented on Source/Events.Handling/IEventHandlerManager.cs
> +    public interface IEventHandlerManager
Same comment as `IFilterManager`

2020-05-12 09:01 UTC, woksin commented on Source/Events.Handling/Internal/EventHandlerProcessor.cs
> +                throw new EventHandlerDoesNotHandleEvent(typeof(TEventType));
You could drop the if-statement in this method and instead have a ThrowIf* method. Like I commented on `AbstractFilterProcessor`

2020-05-12 09:01 UTC, woksin commented on Source/Events.Handling/Internal/ICanHandle.cs
> +    public interface ICanHandle<TEventType>
Same comment as on `ICanHandleEvent`

2020-05-12 09:01 UTC, woksin commented on Source/Events.Handling/InvalidEventHandlerMethodSignature.cs
> +            : base($"The method {methodInfo} on {methodInfo.DeclaringType} {reason}")
That message can be a bit weird depending on what the `reason` might be. Wouldn't it be better like this?
```suggestion
            : base($"The method {methodInfo} on {methodInfo.DeclaringType} is invalid. {reason}")
```

2020-05-12 09:01 UTC, woksin commented on Source/Events/IEventStore.cs
> +        /// <param name="cancellationToken">Token that can be used to cancel this operation.</param>
I guess we can think about whether it makes sense or not to have the `CancellationToken` as a parameter on the methods here

2020-05-12 09:07 UTC, jakhog commented on Source/EventHorizon/SubscriptionBootProcedurePolicy.cs
> +                        }
I can agree with that - probably had more things here before...

2020-05-12 09:09 UTC, jakhog commented on Source/EventHorizon/SubscriptionResponse.cs
> +            if (failure != null) Failure = failure;
True - but this depends on the null handling in the implicit conversions in Fundamentals. Since there is an implicit conversion happening behind the scenes here.

2020-05-12 09:11 UTC, jakhog commented on Source/Events.Filters/EventFiltersProvider.cs
> +            _logger.Debug("Providing {FilterCount} unpartitioned event filters", _unpartitionedFilters.Count());
Not in my opinion, still haven't published any logging guidelines yet, but there should be a Debug log message as an entrypoint to a high level task. So there should always be a Debug message before any traces, so you can enable Debug for a higher log category to see what is going on, then enable trace messages for a specific log category to se the details.

2020-05-12 09:11 UTC, jakhog commented on Source/Events.Filters/EventFiltersProvider.cs
> +            _logger.Debug("Providing {FilterCount} partitioned event filters", _partitionedFilters.Count());
See previous comment.

2020-05-12 09:11 UTC, jakhog commented on Source/Events.Filters/EventHorizon/PublicEventsFilterProvider.cs
> +            _logger.Debug("Providing {FilterCount} public event filters", _filters.Count());
See previous comment.

2020-05-12 09:13 UTC, jakhog commented on Source/Events.Filters/FilterManager.cs
> +    public class FilterManager : IFilterManager
Maybe we should have a talk with the team about this - since we are using Manager many other places in the code and particularly in Fundamentals with e.g. `ExecutionContextManager`. So there should be a common strategy for these names.

2020-05-12 09:15 UTC, jakhog commented on Source/Events.Filters/Internal/AbstractFilterProcessor.cs
> +        }
I know this is a pattern we use other places, but then we get less help from the compiler, and in you suggestion there would need to be another cast operation for it to compile. So I don't personally like this in this very case.

2020-05-12 09:40 UTC, woksin commented on Source/EventHorizon/SubscriptionResponse.cs
> +            if (failure != null) Failure = failure;
Ohh, yes. Makes sense

2020-05-12 09:42 UTC, woksin commented on Source/Events.Filters/FilterManager.cs
> +    public class FilterManager : IFilterManager
Agree. We also have something about this written in our [docs](https://dolittle.io/contributing/guidelines/naming/)

2020-05-12 09:44 UTC, woksin commented on Source/Events.Filters/Internal/AbstractFilterProcessor.cs
> +        }
Another cast operation? I don't know what you mean.

2020-05-14 08:05 UTC, jakhog commented on Source/Events.Filters/Internal/AbstractFilterProcessor.cs
> +        }
The Filter(...) method in the snipped you suggested, takes in an event of `TEventType`, so he suggestion you have won't work as the `typedEvent` variable does not exist. You would have to add something like `var typedEvent = (TEventType)converted.Event;` before that call - which would be the second cast operation.

2020-05-14 08:07 UTC, jakhog commented on Source/Events.Filters/Internal/AbstractFilterProcessor.cs
> +        }
The only other thing I can think of would be to split it out into a method called something like `TryGetTypedEventOrThrowIfIncorrectEventType<TEventType>(IEvent event, out TEventType typedEvent)`. But I'm not sure if that would be easier on the eyes?

2020-05-14 08:11 UTC, jakhog commented on Source/Events.Filters/Internal/ICanFilter.cs
> +    public interface ICanFilter<TEventType, TFilterResult>
It is a classed internally in the SDK in the BootProcedure to share some of the logic while registering the different filter types - which is why I placed it in an `.Internal` namespace. Don't remember exactly why, but the `internal` access modifier don't always play that nice with our things, especially it stops you from using those in the specification projects.

We can get rid of it, but then we need to copy more code in the BootProcedure, or use less strict typing in the code.

2020-05-14 08:15 UTC, jakhog commented on Source/Events.Handling/Builder/EventHandlerInstanceBuilder.cs
> +        where TEventType : IEvent
Hmm, I don't think so, since you pass the instance of the thing in here. Can have a second look, but I would also expect the compiler to complain if I have done something wrong. I think we can leave this as a potential bugfix for later if it turns out to be wrong.

2020-05-14 08:15 UTC, jakhog commented on Source/Events.Handling/Builder/EventHandlerMethod.cs
> +        where TEventType : IEvent;
Same reply as above.

2020-05-14 08:15 UTC, jakhog commented on Source/Events.Handling/ConventionEventHandlerBuilder.cs
> +        public static IEventHandler<TEventType> BuildFor<THandlerType>(FactoryFor<THandlerType> factory)
Again, I don't think so.

2020-05-14 08:18 UTC, jakhog commented on Source/Events.Handling/Internal/ICanHandle.cs
> +    public interface ICanHandle<TEventType>
Same reply - it helps make the code nicer in the boot procedure.

2020-05-14 08:20 UTC, woksin commented on Source/Events.Filters/Internal/AbstractFilterProcessor.cs
> +        }
Ohh, yeah of course... I missed that one. I agree, it would not make it more readable

2020-05-14 08:22 UTC, jakhog commented on Source/Events.Handling/InvalidEventHandlerMethodSignature.cs
> +            : base($"The method {methodInfo} on {methodInfo.DeclaringType} {reason}")
Ok - need to change one of the exceptions to make this work - but not a big thing.

2020-05-14 08:23 UTC, jakhog commented on Source/Events/IEventStore.cs
> +        /// <param name="cancellationToken">Token that can be used to cancel this operation.</param>
I think you should have the ability to cancel all asynchronous method calls - so unless you have a good reason to not allow that, we should keep it.

2020-05-14 08:25 UTC, woksin commented on Source/Events.Filters/Internal/ICanFilter.cs
> +    public interface ICanFilter<TEventType, TFilterResult>
I would prefer to have it, it was just the name that I felt at the moment was a bit odd. But I think that It's fine now, especially since it is in the Internal namespace (did not notice that at the time of review)

Resolving this

2020-05-14 08:33 UTC, jakhog commented on Source/Events.Handling/InvalidEventHandlerMethodSignature.cs
> +            : base($"The method {methodInfo} on {methodInfo.DeclaringType} {reason}")
Fixed in accd137f60b18152b8691297a5473c5861b261aa

2020-05-14 08:36 UTC, woksin commented on Source/Events.Handling/InvalidEventHandlerMethodSignature.cs
> +            : base($"The method {methodInfo} on {methodInfo.DeclaringType} {reason}")
Nice

2020-05-14 08:45 UTC, jakhog commented on Source/Events.Handling/EventHandlersProvider.cs
> +            _logger.Debug("Providing {EventHandlerCount} event handlers", _handlers.Count());
See previous comment for EventFiltersProvider.cs

2020-05-14 08:46 UTC, jakhog commented on Source/Events.Handling/EventHorizon/ExternalEventHandlersProvider.cs
> +            _logger.Debug("Providing {EventHandlerCount} external event handlers", _handlers.Count());
See previous comment for EventFiltersProvider.cs

2020-05-14 08:47 UTC, jakhog commented on Source/Events.Handling/Internal/EventHandlerProcessor.cs
> +                throw new EventHandlerDoesNotHandleEvent(typeof(TEventType));
Same as in AbstractFilterProcessor.cs as you say - so I guess we agreed that it is OK to keep it like this for now?

2020-05-14 08:57 UTC, woksin commented on Source/Events/IEventStore.cs
> +        /// <param name="cancellationToken">Token that can be used to cancel this operation.</param>
Yes I agree

2020-05-14 08:58 UTC, jakhog commented on Source/Events.Handling/ConventionEventHandlerBuilder.cs
> +                    }
Fixed in 680ea2a3f76bcb9b17be8ab9a517216e35aa028b

2020-05-14 08:58 UTC, jakhog commented on Source/Events.Handling/ConventionEventHandlerBuilder.cs
> +                }
Fixed in 680ea2a3f76bcb9b17be8ab9a517216e35aa028b

2020-05-14 09:18 UTC, jakhog commented on Source/Events.Filters/FilterManager.cs
> +    public class FilterManager : IFilterManager
Fixed in 81399a1e8f6e0cf29430d8e06aa3a0cb4a877e1b

2020-05-14 09:18 UTC, jakhog commented on Source/Events.Filters/FilterManagerPolicy.cs
> +    public class FilterManagerPolicy : IDefineAsyncPolicyForType
Fixed in 81399a1e8f6e0cf29430d8e06aa3a0cb4a877e1b

2020-05-14 09:18 UTC, jakhog commented on Source/Events.Filters/IFilterManager.cs
> +    public interface IFilterManager
Fixed in 81399a1e8f6e0cf29430d8e06aa3a0cb4a877e1b

2020-05-14 09:18 UTC, jakhog commented on Source/Events.Handling/EventHandlerManager.cs
> +    public class EventHandlerManager : IEventHandlerManager
Fixed in 74f68d1ce607f20c0ff1f41c54bf203ca10645cb

2020-05-14 09:19 UTC, jakhog commented on Source/Events.Handling/EventHandlerManagerPolicy.cs
> +    public class EventHandlerManagerPolicy : IDefineAsyncPolicyForType
Fixed in 74f68d1ce607f20c0ff1f41c54bf203ca10645cb

2020-05-14 09:19 UTC, jakhog commented on Source/Events.Handling/IEventHandlerManager.cs
> +    public interface IEventHandlerManager
Fixed in 74f68d1ce607f20c0ff1f41c54bf203ca10645cb

2020-05-14 09:44 UTC, woksin approved these changes
Nice stuff! Let's get this in

2020-05-14 09:45 UTC, merged